[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/**"]
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"